spring:
  data:
    #Redis相关配置
    redis:
      host: localhost
      port: 6379
      password: 8888.216
      database: 1 #默认操作的是0号数据库
    name: mySpring-data-redis
    lettuce:
      #Redis连接池配置
      pool:
        max-active: 1024 #最大连接数
        max-wait: 10000ms #连接池最大阻塞等待时间
        max-idle: 200 #连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
